--drop table if exists member CASCADE;
--create table member
--(
--    idx bigint generated by default as identity,
--    email varchar(255),
--    name varchar(255),
--    pwd varchar(255),
--    primary key (idx)
--);

insert into member(email, name, pwd) values('test@test.com', '박미미', '1111');
insert into member(email, name, pwd) values('abc@def.com', '김미미', 'asdf');