drop table if exists member CASCADE;
create table member
(
    idx bigint generated by default as identity,
    email varchar(255),
    name varchar(255),
    pwd varchar(255),
    primary key (idx)
);