create database pos;
use pos;
commit;

create table member
(
   idx bigint generated by default as identity,
   email varchar(255),
   name varchar(255),
   pwd varchar(255),
   primary key (idx)
);

create table home(
	name VARCHAR(70),
    lat double,
    lng double
);

CREATE TABLE test (
    Housing_Management_Number INT,
    Public_Notice_Number INT,
    Housing_Name VARCHAR(255),
    Housing_Categtestory_Code INT,
    Housing_Category_Name VARCHAR(255),
    Housing_Detail_Category_Code INT,
    Housing_Detail_Category_Name VARCHAR(255),
    Sales_Type_Code INT,
    Sales_Type_Name VARCHAR(255),
    Supply_Area_Code INT,
    Supply_Area_Name VARCHAR(255),
    Supply_Location_Postal_Code VARCHAR(20),
    Supply_Location VARCHAR(255),
    Supply_Scale VARCHAR(50),
    Recruitment_Notice_Date DATE,
    Application_Start_Date DATE,
    Application_End_Date DATE,
    Special_Supply_Start_Date DATE,
    Special_Supply_End_Date DATE,
    1st_Priority_Application_Date_Local_Area DATE,
    1st_Priority_Application_Date_Gyeonggi_Area DATE,
    1st_Priority_Application_Date_Other_Areas DATE,
    2nd_Priority_Application_Date_Local_Area DATE,
    2nd_Priority_Application_Date_Gyeonggi_Area DATE,
    2nd_Priority_Application_Date_Other_Areas DATE,
    Winner_Announcement_Date DATE,
    Contract_Start_Date DATE,
    Contract_End_Date DATE,
    Website_Address VARCHAR(255),
    Construction_Company_or_Contractor VARCHAR(255),
    Contact_Information VARCHAR(255),
    Business_Entity_or_Implementing_Agency VARCHAR(255),
    Expected_Move_in_Month VARCHAR(20),
    Speculative_Overheated_Zone VARCHAR(20),
    Adjustment_Target_Area VARCHAR(255),
    Price_Ceiling_for_Sales INT,
    Redevelopment_Project VARCHAR(20),
    Public_Housing_Zone VARCHAR(20),
    Large_Scale_Land_Development_Zone VARCHAR(20),
    Privately_Owned_Public_Housing_Zone_within_the_Capital_Region VARCHAR(20),
    Recruitment_Notice_URL VARCHAR(255)
);

LOAD DATA LOCAL INFILE 'C:/Users/user1/Downloads/test.csv'
INTO TABLE pos.test
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
/*여기 코드에서 위에는 파일 경로 넣어주시면 mysql에서 csv파일 임포트 가능합니당*/